### ISSUE TITLE
Documentation on usage?

### ISSUE THREAD

**Issue by ferventcoder** [coveralls-net/coveralls.net#5]
So what I gather from code-cracker issue is that I need to do something similar to this - https://github.com/code-cracker/code-cracker/blob/master/build.targets.ps1#L195-L198

It would be really nice to see some documentation here though.

**Comment by jdeering** [comment]
There is an example of usage in this project's appveyor.yml file. I will make sure to update this project with other usage examples as well. Thanks.

**Comment by ferventcoder** [comment]
Sweet! Got something working, however I'm not sure how well it is going to work on Mono/Ubuntu (Travis CI) - not your fault, OpenCover seems to have issues over there.

**Comment by kbilsted** [comment]
The readme should point to some example. It's really unclear how to get started. Partly also due to the lack of information on https://coveralls.io/ they basically just point to your nuget repo.

So the idea is to: 
- Have a nuget dependency to your project from ones test project
- Include a .yml file with configuration
- Build the project using appveyor
- your tool then submits data to coverall.net which then publishes?

or how far off am I?

Also, how to best deal with security tokens now that coverall.net advices not to add the token to the .yml file?

**Comment by ferventcoder** [comment]
Appveyor has a tool for putting an enctypted token in the yaml file. You
can see an example in this project's yaml file.

On Sunday, February 8, 2015, Kasper B. Graversen notifications@github.com
wrote:

> The readme should point to some example. It's really unclear how to get
> started. Partly also due to the lack of information on
> https://coveralls.io/ they basically just point to your nuget repo.
> 
> So the idea is to
> - Have a nuget dependency to your project from ones test project
> - Include a .yml file with configuration
> - Build the project using appveyor
> - your tool then submits data to coverall.net which then publishes?
> 
> how to best deal with security tokens now that coverall.net advices not
> to add the token to the .yml file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jdeering/coveralls.net/issues/5#issuecomment-73399885
> .

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by kbilsted** [comment]
Yeah I found it after much searching https://ci.appveyor.com/tools/encrypt

do you want a pullrequest with an updated README.MD detailing how to get started?

**Comment by jdeering** [comment]
I definitely won't say no to help offered. I'm open to any and all contributions via pull requests if they help advance the tool and/or its usage.

**Comment by ferventcoder** [comment]
Here's how I implemented it in Chocolatey using UppercuT:
- https://github.com/chocolatey/choco/commit/b5b3c24d1e55448226dc37d1cb4b91c451fcf713
- https://github.com/chocolatey/choco/commit/83000dde97cf2d1d0627ed3ca067d32d95e5cd6b <- most of the work is done here
- https://github.com/chocolatey/choco/commit/ac86134b42f6cba474a5408a374dc21efe69151e

**Comment by kbilsted** [comment]
@ferventcoder  how do you like my latest changes to the readme.md ?

**Comment by ferventcoder** [comment]
Ship it. :shipit: :+1:

**Comment by kbilsted** [comment]
What do you mean @ferventcoder  ? it has already been merged. Do you mean close this issue?

**Comment by ferventcoder** [comment]
Sorry. It's a saying meant to mean good to go.

**Comment by jdeering** [comment]
Thoughts on placing the **Getting Started** in wiki instead of README.md? I understand the benefit of it being right on the front page, but we're making assumptions about build environments as well as enforcing a specific project layout via the instructions used. I'd rather see a few **Getting Started** options, especially a quick, local build and run option that doesn't require a CI service. And I would personally prefer the quick start/local option to the Appveyor option as the default in README.md.

I figured I would ask instead of dictate as you both seem to be using this a lot more than I am at the moment. Although hopefully I'll be a little more active in the coming weeks.

**Comment by ferventcoder** [comment]
Wiki works for me. :)

On Monday, February 16, 2015, Jason Deering notifications@github.com
wrote:

> Thoughts on placing the _Getting Started_ in wiki instead of README.md? I
> understand the benefit of it being right on the front page, but we're
> making assumptions about build environments as well as enforcing a specific
> project layout via the instructions used. I'd rather see a few _Getting
> Started_ options, especially a quick, local build and run option that
> doesn't require a CI service. And I would personally prefer the quick
> start/local option to the Appveyor option as the default in README.md.
> 
> I figured I would ask instead of dictate as you both seem to be using this
> a lot more than I am at the moment. Although hopefully I'll be a little
> more active in the coming weeks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jdeering/coveralls.net/issues/5#issuecomment-74520044
> .

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by kbilsted** [comment]
Fine with me too. As long as the readme points to the wiki:)

How do you version the wiki? Wondered myself about documentation. My stateprinter project uses a doc folder instead and has the readme point into the doc folder. This project and mine are for programmers so I'm not sure you will see more edits on the wiki.

**Comment by kbilsted** [comment]
https://github.com/kbilsted/StatePrinter

**Comment by jdeering** [comment]
I've started wiki pages for documentation of usage. If anyone wants to help contribute, let me know and I'll add the relevant permissions.
